---
# The check-config workflow will run the Prometheus 'promtool' and
# 'amtool' config validation checks against the config files in the repo.
name: Check-Config

on:
  pull_request:
    paths:
      - '**/prometheus-config.yml'
      - '**/alert-config.yml'
  workflow_call:

jobs:
  check-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Generate config files
        run: |
          envsubst < prometheus/prometheus-config.yml > prometheus/prometheus.yml
          envsubst < alertmanager/alert-config.yml > alertmanager/alertmanager.yml
        env:
          # Use 'fake' environment variables since we're just checking syntax
          ENVIRONMENT_NAME: dev
          SLACK_URL: https://slack.com

      - name: Validate Prometheus Config
        run: |
          ./install_prometheus.sh
          ./promtool check config prometheus.yml
          ./promtool check rules rules.yml
        working-directory: ./prometheus

      - name: Validate Alertmanager Config
        run: |
          ./install_alertmanager.sh
          ./amtool check-config alertmanager.yml
        working-directory: ./alertmanager
