---
name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - '**.md'  # All markdown files in the repository
  release:
    types: [released]

jobs:
  check-config:
    uses: 18F/identity-idva-monitoring/.github/workflows/check-config.yaml@main

  deploy:
    if: github.repository_owner == '18F'
    needs: check-config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: 18F/identity-idva-cf-setup@v2
        id: cf-setup
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}

      - name: Generate config files
        run: |
          envsubst < alertmanager/alert-config.yml > alertmanager/alertmanager.yml
        env:
          ENVIRONMENT_NAME: ${{ steps.cf-setup.outputs.target-environment }}
          SLACK_URL: ${{ secrets.SLACK_URL }}

      - name: Deploy Cortex
        run: cf push --vars-file vars.yaml
          --var ENVIRONMENT_NAME=${{ steps.cf-setup.outputs.target-environment }}
          --strategy rolling
        working-directory: ./cortex

      - name: Deploy Alertmanager
        run: cf push
          --var ENVIRONMENT_NAME=${{ steps.cf-setup.outputs.target-environment }}
          --var SLACK_URL=${{ secrets.SLACK_URL }}
          --memory 64MB
          --instances 2
          --strategy rolling
        working-directory: ./alertmanager

      - name: Deploy Prometheus
        run: cf push --vars-file vars.yaml
          --var ENVIRONMENT_NAME=${{ steps.cf-setup.outputs.target-environment }}
          --strategy rolling
        working-directory: ./prometheus

      - name: Deploy Grafana
        run: cf push
          --var ENVIRONMENT_NAME=${{ steps.cf-setup.outputs.target-environment }}
          --var GRAFANA_PASS=${{ secrets.GRAFANA_PASS }}
          --strategy rolling
        working-directory: ./grafana

      - name: Apply CF Network Policies
        run: |
          # Alertmanager gossip routes
          cf add-network-policy alertmanager alertmanager --protocol tcp --port 9094
          cf add-network-policy alertmanager alertmanager --protocol udp --port 9094
          # Cortex routes
          cf add-network-policy prometheus cortex
          cf add-network-policy grafana cortex
          # Prometheus routes
          cf add-network-policy prometheus alertmanager
          cf add-network-policy prometheus cf-metrics
          cf add-network-policy prometheus redis-metrics
          cf add-network-policy prometheus elasticsearch-metrics
          cf add-network-policy prometheus kong --port 8100 --protocol tcp
          # Grafana routes
          cf add-network-policy grafana prometheus
          cf add-network-policy prometheus grafana
