---
# This workflow will run periodically to check for new releases of prometheus
# and create pr to update the version when available

name: Update

on:
  schedule:
    - cron: '23 7 * * *'
  workflow_dispatch:
jobs:
  prometheus:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Version of Prometheus
        run: ./version_updater.sh ./prometheus/VERSION https://api.github.com/repos/prometheus/prometheus/releases/latest

      - name: Create PR
        uses: peter-evans/create-pull-request@v4.1.4
        with:
          title: Bump Prometheus version from ${{ env.CURRENT_VERSION }} -> ${{ env.LATEST_VERSION }}
          body: '[Prometheus ${{env.LATEST_VERSION}} release](${{env.HTML_URL}})'
          commit-message: Bump Prometheus version to ${{ env.LATEST_VERSION }}
          branch: bump-prometheus-version
          reviewers: |
            18f/idva-partners

  alertmanager:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Version of Alertmanager
        run: ./version_updater.sh ./alertmanager/VERSION https://api.github.com/repos/prometheus/alertmanager/releases/latest

      - name: Create PR
        uses: peter-evans/create-pull-request@v4.1.4
        with:
          title: Bump Alertmanager version from ${{ env.CURRENT_VERSION }} -> ${{ env.LATEST_VERSION }}
          body: '[Alertmanager ${{env.LATEST_VERSION}} release](${{env.HTML_URL}})'
          commit-message: Bump Alertmanager version to ${{ env.LATEST_VERSION }}
          branch: bump-alertmanager-version
          reviewers: |
            18f/idva-partners

  cortex:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Version of Cortex
        run: ./version_updater.sh ./cortex/VERSION https://api.github.com/repos/cortexproject/cortex/releases/latest

      - name: Create PR
        uses: peter-evans/create-pull-request@v4.1.4
        with:
          title: Bump Cortex version from ${{ env.CURRENT_VERSION }} -> ${{ env.LATEST_VERSION }}
          body: '[Cortex ${{env.LATEST_VERSION}} release](${{env.HTML_URL}})'
          commit-message: Bump Cortex version to ${{ env.LATEST_VERSION }}
          branch: bump-cortex-version
          reviewers: |
            18f/idva-partners
